# name
name: hello_world

# trigger
on: 
- push

# one or more jobs
jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - id: s00
      run: echo "Current time in GitHub is $(date)"
    - id: s01
      uses: mscoutermarsh/cowsays-action@master
      with :
        text: 'Moo moo cow!'
        color: 'green'
      
